# Generated by Django 5.2 on 2026-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_category_remove_comment_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('jamisyet', 'Jámiyet'), ('siyasat', 'Siyasat'), ('ekonomika', 'Ekonomika'), ('sport', 'Sport'), ('madeniyat', 'Mádeniyat'), ('siyahat', 'Sayaxat')], default='jamisyet', max_length=50),
        ),
    ]
